# Generated by Django 2.2.5 on 2019-11-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191111_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='purchased_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
